### ISSUE TITLE
Cand userul intra pe homepage, in User Journey arata "Visit the help\faq page"

### ISSUE THREAD

**Issue by Tynael** [retargeting/Shoper#1]
Cand userul intra pe homepage, in User Journey arata "Visit the help\faq page", chiar daca FAQ/HELP page sau o alta pagina nu a fost accesata.

![visit help faq page](https://cloud.githubusercontent.com/assets/16559614/15928351/1045ba80-2e4f-11e6-8b18-cc507915f77e.jpg)

**Comment by cosminatomei** [comment]
am rezolvat. Trailing slash issue..
