### ISSUE TITLE
Imaginea produsului nu este captata cum trebuie

### ISSUE THREAD

**Issue by Tynael** [retargeting/Shoper#10]
Imaginea produsului nu este captata cum trebuie.
In Network poti observa ca la "img" la Query String Parameters linkul este unul invalid.

![imgparameter](https://cloud.githubusercontent.com/assets/16559614/16150008/3a9da636-349d-11e6-823c-a4e3b3c97a4b.jpg)

**Comment by cosminatomei** [comment]
Solved, apparently they use the "unic_name" and not the "gfx_id".
