### ISSUE TITLE
sendProduct nu functioneaza. In DevTools nu ia niciun parametru

### ISSUE THREAD

**Issue by Tynael** [retargeting/Shoper#2]
sendProduct nu functioneaza. In DevTools nu ia niciun parametru si, obviously, in User Journey nu apare produsul.

![sendproduct parameters](https://cloud.githubusercontent.com/assets/16559614/15928419/5f85c9dc-2e4f-11e6-9ff8-10e17a62690b.jpg)

**Comment by cosminatomei** [comment]
Tokens-urile expirasera.. a expirat inclusiv refresh_token-ul care trebuie folosit la reinitierea token-urilor :))
