### ISSUE TITLE
sendCategory nu functioneaza. Nu apare in User Journey.

### ISSUE THREAD

**Issue by Tynael** [retargeting/Shoper#3]
sendCategory nu functioneaza. Nu apare in User Journey.
![sendcategory parameters](https://cloud.githubusercontent.com/assets/16559614/15928454/97938882-2e4f-11e6-81fd-54c1a073c00c.jpg)

**Comment by cosminatomei** [comment]
Same as for SendProduct. The tokens have long been expired.
