### ISSUE TITLE
mouseOverImage nu functioneaza.

### ISSUE THREAD

**Issue by Tynael** [retargeting/Shoper#4]
mouseOverImage nu functioneaza. Nu se porneste niciun event cand cursorul se plimba pe imaginea produsului.

**Comment by cosminatomei** [comment]
.. a existat functionalitatea asta pana acum? nu e nici in documentatia noua.

https://retargeting.biz/documentation/

**Comment by cosminatomei** [comment]
acum am inteles.. e clickImage..

**Comment by cosminatomei** [comment]
Dar clickImage merge.. sooo .. :))
