### ISSUE TITLE
add2Cart nu apare in User Journey

### ISSUE THREAD

**Issue by Tynael** [retargeting/Shoper#6]
add2Cart nu apare in User Journey. Eventul apare in Network de la DevTools.
![add2cart parameters](https://cloud.githubusercontent.com/assets/16559614/15928569/49415870-2e50-11e6-8a46-ecdff9684731.jpg)

**Comment by cosminatomei** [comment]
Am reverificat structura requestului dupa documentatie si vad ca primim si raspuns standardizat inapoi:
`_ra.response({"agid": "5762a606d5bc6da7028d5a59", "sesid": "5762a606d5bc6da7028d5a5a", "email": undefined, "callback": 0, "errors": [], "log": [], "req": "addToCart"});`

In conditiile astea, feature-ul App-ului functioneaza. (conform documentatiei) E o inconsistenta intre ce se asteapta serverul sa primeasca si ce trimite App-ul. Problema e ca fara mai multe informatii din partea serverului, nu prea putem face nimic noi..

Trebuie sa vedeti de ce, pe partea de Server, nu se interpreteaza requestul. Probabil nu accepta diverse Caractere speciale, etc..
