### ISSUE TITLE
add2Wishlist nu functioneaza

### ISSUE THREAD

**Issue by Tynael** [retargeting/Shoper#9]
add2Wishlist nu functioneaza. Nu porneste niciun event, nu apare nimic in Network si nici in User Journey.

**Comment by cosminatomei** [comment]
Tocmai am retestat si apare in Network (de User Journey revenim la discutia de la addToCart - nu tine de noi).

`Request URL:https://tracking.retargeting.biz/v3/rareq/ra.ev?k=MYPMNJDS6XN5KC&t=ev&d=http%3A%2F%2Fdevshop-63421.shoparena.pl%2Fpl%2Fp%2FSpodnica-4F-wieczorowa%2F13&bws=Chrome%2051&cm=add_to_wishlist&id=13&callback=0&agid=5762a606d5bc6da7028d5a59&sesid=5762a606d5bc6da7028d5a5a
Request Method:GET
Status Code:200 OK
Remote Address:144.76.136.72:443`

Am primit raspunsul acesta de la server:
`_ra.response({"agid": "5762a606d5bc6da7028d5a59", "sesid": "5762a606d5bc6da7028d5a5a", "email": undefined, "callback": 0, "errors": [], "log": [], "req": "addToWishlist"});`
